script:
- 'git config git-ftp.url ftp://${url}''
- 'git config git-ftp.user ${username}''
- 'git config git-ftp.password ${password}''
- 'git clone https://github.com/itoktoni/travis.git'
- 'dir'
- 'cd travis'
- 'git ftp init'