install:
script:
 - apt-get update -qq && apt-get install -y -qq lftp
- git clone https://github.com/itoktoni/travis.git
- lftp -c "open -u $username,$password ftp.ptibm.id; set ssl:verify-certificate no; mirror -R travis/ /apps/demo/travis"