install:
- git clone https://github.com/git-ftp/git-ftp.git
- cd git-ftp
- git checkout 1.1.0
- sudo make install
script:
- git clone https://github.com/itoktoni/travis.git
- dir
- cd travis
- git config git-ftp.url "${$url}"
- git config git-ftp.user "${username}@${url}"
- git config git-ftp.password "${password}"
- git ftp catchup