before_install:
  - sudo apt-get update
  - sudo apt-get install -y lftp
script:
- git clone https://github.com/itoktoni/travis.git
- lftp -c "open -u itoktoni@ptibm.id,0215443294 ftp.ptibm.id; set ssl:verify-certificate no; mirror -R travis/ /apps/demo/travis"